"""fixed phone number error

Revision ID: 769792cefa88
Revises: ebda4aae6e18
Create Date: 2023-02-28 16:03:39.233294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769792cefa88'
down_revision = 'ebda4aae6e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
