"""empty message

Revision ID: cc6139c39502
Revises: 6944c3816742
Create Date: 2023-03-01 00:54:44.179116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6139c39502'
down_revision = '6944c3816742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.drop_column('id_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_no', sa.INTEGER(), nullable=True))
        batch_op.drop_column('points')
        batch_op.drop_column('phone_no')

    # ### end Alembic commands ###
