"""employees table created

Revision ID: fe49cbbc67fc
Revises: cc6139c39502
Create Date: 2023-03-01 11:20:35.802310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe49cbbc67fc'
down_revision = 'cc6139c39502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_no', sa.Integer(), nullable=True),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('hash_password', sa.Integer(), nullable=True),
    sa.Column('hash_pin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_id_no'), ['id_no'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_id_no'))

    op.drop_table('employees')
    # ### end Alembic commands ###
